- name: creating the Security Group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group to test Ansible
    region: "{{ region  }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ allowed_ip }}"
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: creating EC2 instance
  local_action: ec2
    group={{ security_group  }}
    instance_type={{ instance_type  }}
    image={{ image  }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Adding the instance into a temp inventory
  add_host: name={{ item.public_ip }} groups=ansible-new
  with_items: "{{ ec2.instances }}"

- name: Addding the instance into the hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[testansible]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Wating for ssh
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: adding a tag tag name to instance
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: TestAnsible

